<?php

namespace poznet\FakturaBundle\Repository;

/**
 * FakturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FakturaRepository extends \Doctrine\ORM\EntityRepository
{
}
