<?php

namespace poznet\FakturaBundle\Repository;

/**
 * FakturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FakturaRepository extends \Doctrine\ORM\EntityRepository
{

    public function findLastNumberForMonth(\DateTime $data)
    {
        $result = $this->getEntityManager()->createQuery('
        SELECT F from FakturaBundle:Faktura F
        WHERE MONTH(F.data_wystawienie)=:miesiac
        ORDER BY F.id DESC 
        ')
            ->setParameter('miesiac', $data->format('m'))
            ->getFirstResult();

        return $result;
    }

    public function findByMiesiac($rok, $miesiac)
    {
        $qb = $this->createQueryBuilder('f')
            ->andWhere('f.dataWystawienia  LIKE :forDate')
            ->setParameter('forDate', $rok . '-' . $miesiac . '-%')
            ->getQuery();
        return $qb->execute();
    }
}
