doctrine:
    orm:
        entity_managers:
            default:
                dql:
                    string_functions:
                        MONTH: Poznet\CoreBundle\Dql\Month
                        YEAR: Poznet\CoreBundle\Dql\Year