services:
#    poznet_faktura.example:
#        class: poznet\FakturaBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    poznet_faktura_number_service:
        class: FakturaBundle\src\poznet\FakturaBundle\Service\FakturaNumberService

    poznet_faktura_umber_event_listener:
        class: FakturaBundle\src\poznet\FakturaBundle\EventListener\FakturaNumberListener
        tags:
            - { name: doctrine.event_listener, event: postPersist, lazy: true }