services:
#    poznet_faktura.example:
#        class: poznet\FakturaBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    poznet_faktura_service:
        class: FakturaBundle\src\poznet\FakturaBundle\Service\FakturaNumberService
        arguments: ['@kernel','@doctrine.orm.entity_manager']

    poznet\FakturaBundle\Form\FakturaType:
        tags: [form.type]
        arguments: ['@kernel']
